#pragma once

#include <stdbool.h>
#include <stdint.h>

void uvc_stream_init(void);
void uvc_stream_start(void);
void uvc_stream_stop(void);
bool uvc_stream_is_active(void);
bool uvc_stream_needs_sof_poll(void);
bool uvc_stream_needs_iso_retry(void);
bool uvc_stream_waiting_for_frame_interval(void);

void uvc_stream_process(void);
void uvc_stream_poll_pending(void);
bool uvc_stream_send_start_payload(void);
void uvc_stream_on_sof(void);
void uvc_stream_on_tx_complete(void);
void uvc_stream_on_iso_incomplete(void);
void uvc_stream_on_iso_incomplete_minimal(void);
void uvc_stream_watchdog_poll(void);
void uvc_stream_abort_frame(void);
bool uvc_stream_retry_last_packet(void);
uint32_t uvc_stream_get_offset(void);
uint32_t uvc_stream_get_packet_count(void);
uint32_t uvc_stream_get_frame_size(void);
uint32_t uvc_stream_get_preamble_sent(void);
uint32_t uvc_stream_get_reopen_pending(void);

bool uvc_lowlevel_transmit(uint8_t *data, uint16_t len);
bool uvc_lowlevel_reopen_stream_ep(void);

/* debug */
extern volatile uint32_t uvc_packets_sent;
extern volatile uint32_t uvc_frames_sent;
extern volatile uint32_t uvc_stream_process_calls;
extern volatile uint32_t uvc_tx_complete_calls;
extern volatile uint32_t uvc_stream_start_calls;
extern volatile uint32_t uvc_stream_start_attempts;
extern volatile uint32_t uvc_stream_start_already_active;
extern volatile uint32_t uvc_stream_start_no_frame;
extern volatile uint32_t uvc_last_offset;
extern volatile uint32_t uvc_last_frame_size;
extern volatile uint32_t uvc_eof_hits;
extern volatile uint32_t uvc_commit_attempts;
extern volatile uint32_t uvc_current_frame_size_dbg;
extern volatile const uint8_t *uvc_current_frame_ptr_dbg;
extern volatile uint32_t uvc_frame_pace_skips;
extern volatile uint8_t uvc_first_payload_b0;
extern volatile uint8_t uvc_first_payload_b1;
extern volatile uint8_t uvc_first_payload_b2;
extern volatile uint8_t uvc_first_payload_b3;
extern volatile uint8_t uvc_last_payload_b0;
extern volatile uint8_t uvc_last_payload_b1;
extern volatile uint8_t uvc_last_payload_b2;
extern volatile uint8_t uvc_last_payload_b3;
extern volatile uint8_t uvc_last_header_b0;
extern volatile uint8_t uvc_last_header_b1;
extern volatile uint32_t uvc_frame_interval_ms;
extern volatile uint32_t uvc_frame_payload_bytes;
extern volatile uint32_t uvc_frame_packet_count;
extern volatile uint32_t uvc_last_frame_payload_bytes;
extern volatile uint32_t uvc_last_frame_packet_count;
extern volatile uint32_t uvc_last_frame_expected_packets;
extern volatile uint32_t uvc_frame_integrity_ok;
extern volatile uint32_t uvc_frame_integrity_fail;
extern volatile uint32_t uvc_non_eof_short_packets;
extern volatile uint32_t uvc_eof_short_packets;
extern volatile uint32_t uvc_last_frame_checksum;
extern volatile uint32_t uvc_frame_checksum;
extern volatile uint32_t uvc_iso_frame_drops;
extern volatile uint32_t uvc_iso_incomplete_minimal_calls;
extern volatile uint32_t uvc_iso_incomplete_ignored;
extern volatile uint32_t uvc_iso_immediate_resync_calls;
extern volatile uint32_t uvc_iso_incomplete_continue_calls;
extern volatile uint32_t uvc_iso_incomplete_idle_reopen;
extern volatile uint32_t uvc_iso_class_retry_calls;
extern volatile uint32_t uvc_iso_class_retry_ok;
extern volatile uint32_t uvc_iso_class_retry_fail;
extern volatile uint32_t uvc_iso_class_retry_idle;
extern volatile uint32_t uvc_iso_class_retry_suppressed;
extern volatile uint32_t uvc_iso_incomplete_drop_enable;
extern volatile uint32_t uvc_iso_consecutive_incomplete_dbg;
extern volatile uint32_t uvc_iso_reopen_after_incomplete_burst;
extern volatile uint32_t uvc_iso_reopen_threshold;
extern volatile uint32_t uvc_recovery_eof_packets;
extern volatile uint32_t uvc_frame_interval_releases;
extern volatile uint32_t uvc_frame_preamble_packets;
extern volatile uint32_t uvc_frame_keepalive_packets;
extern volatile uint32_t uvc_frame_keepalive_enable;
extern volatile uint32_t uvc_frame_keepalive_interval_ms;
extern volatile uint32_t uvc_start_payload_calls;
extern volatile uint32_t uvc_start_payload_ok;
extern volatile uint32_t uvc_start_payload_fail;
extern volatile uint32_t uvc_first_payload_defer_calls;
extern volatile uint32_t uvc_first_payload_releases;
extern volatile uint32_t uvc_first_payload_wait_skips;
extern volatile uint32_t uvc_first_payload_delay_ms;
extern volatile uint32_t uvc_next_packet_main_releases;
extern volatile uint32_t uvc_datain_direct_process_enable;
extern volatile uint32_t uvc_tx_watchdog_timeout_ms;
extern volatile uint32_t uvc_tx_watchdog_calls;
extern volatile uint32_t uvc_tx_watchdog_recoveries;
extern volatile uint32_t uvc_tx_watchdog_reopen_ok;
extern volatile uint32_t uvc_last_tx_complete_tick;
extern volatile uint32_t uvc_process_tx_in_flight_skips;
extern volatile uint32_t uvc_dbg_state_live;
extern volatile uint32_t uvc_dbg_wait_frame_interval;
extern volatile uint32_t uvc_dbg_wait_first_payload;
extern volatile uint32_t uvc_dbg_wait_next_packet;
extern volatile uint32_t uvc_dbg_iso_retry_ready;
extern volatile uint32_t uvc_dbg_pending_payload_active;
extern volatile uint32_t uvc_dbg_pending_payload_len;
extern volatile uint32_t uvc_dbg_offset_live;
extern volatile uint32_t uvc_dbg_frame_size_live;
extern volatile uint32_t uvc_dbg_frame_elapsed_ms;
extern volatile uint32_t uvc_dbg_payload_send_calls;
extern volatile uint32_t uvc_dbg_payload_send_ok;
extern volatile uint32_t uvc_dbg_payload_send_fail;
extern volatile uint32_t uvc_dbg_payload_last_offset;
extern volatile uint32_t uvc_dbg_payload_last_data_len;
extern volatile uint32_t uvc_dbg_payload_last_total_len;
extern volatile uint32_t uvc_dbg_payload_last_eof;
extern volatile uint32_t uvc_dbg_payload_first_toggle;
extern volatile uint32_t uvc_dbg_commit_calls;
extern volatile uint32_t uvc_dbg_commit_last_offset;
extern volatile uint32_t uvc_stall_recover_enable;
extern volatile uint32_t uvc_stall_recoveries;
extern volatile uint32_t uvc_stall_recover_state;
extern volatile uint32_t uvc_stall_recover_in_flight;
extern volatile uint32_t uvc_stall_recover_reopen_attempts;
extern volatile uint32_t uvc_stall_recover_reopen_ok;
extern volatile uint32_t uvc_stall_recover_min_interval_ms;
extern volatile uint32_t uvc_stall_recover_backoff_skips;
extern volatile uint32_t uvc_frame_stall_guard_enable;
extern volatile uint32_t uvc_frame_stall_timeout_ms;
extern volatile uint32_t uvc_frame_stall_stops;
extern volatile uint32_t uvc_frame_stall_direct_next_enable;
extern volatile uint32_t uvc_frame_stall_force_next_calls;
extern volatile uint32_t uvc_frame_stall_tick;
extern volatile uint32_t uvc_frame_stall_frames_sent;
extern volatile uint32_t uvc_frame_stall_tx_complete_calls;
extern volatile uint32_t uvc_frame_stall_state;
extern volatile uint32_t uvc_frame_stall_wait_frame_interval;
extern volatile uint32_t uvc_frame_stall_offset;
extern volatile uint32_t uvc_frame_stall_frame_size;
extern volatile uint32_t uvc_recover_eof_sof_polls;
extern volatile uint32_t uvc_recover_eof_timeout_ms;
extern volatile uint32_t uvc_recover_eof_timeouts;
extern volatile uint32_t uvc_recover_eof_timeout_state;
extern volatile uint32_t uvc_recover_eof_timeout_in_flight;
extern volatile uint32_t uvc_recover_eof_reopen_ok;
