#ifndef USB_STACK_SELECT_H
#define USB_STACK_SELECT_H

#define UVC_USB_STACK_CLASSIC          0U
#define UVC_USB_STACK_USBX_STANDALONE  1U

#ifndef UVC_USB_STACK
#define UVC_USB_STACK UVC_USB_STACK_USBX_STANDALONE
#endif

#define UVC_USB_STACK_IS_CLASSIC (UVC_USB_STACK == UVC_USB_STACK_CLASSIC)
#define UVC_USB_STACK_IS_USBX    (UVC_USB_STACK == UVC_USB_STACK_USBX_STANDALONE)

#endif /* USB_STACK_SELECT_H */
